name        : pantheon-terminal
version     : 0.3.2
release     : 8
source     :
    - https://launchpad.net/pantheon-terminal/0.3.x/0.3.2/+download/pantheon-terminal-0.3.2.tar.xz : 57ac969d64ffa0648f942df7d5ef99efae83beff648d810cb9833ba32d9a75c0
license     :
    - GPLv3+
summary     : A super lightweight, beautiful, and simple terminal.
builddeps   :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(granite)
    - pkgconfig(vte-2.91)
    - pkgconfig(libnotify)
    - vala
description : |
    A super lightweight, beautiful, and simple terminal. It's designed to be setup with sane defaults and little to no configuration. It's just a terminal, nothing more, nothing less.
    
    Designed for elementary OS.
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
