name       : pantheon-terminal
version    : 5.3.6
release    : 18
source     :
    - https://github.com/elementary/terminal/archive/5.3.6.tar.gz : c3e01bd11788c9c65a604ae5653a0bead8a35635a46268e329690dc841eef18a
license    : GPL-3.0-only
component  : desktop
summary    : A super lightweight, beautiful, and simple terminal.
description: |
    A super lightweight, beautiful, and simple terminal. It's designed to be setup with sane defaults and little to no configuration. It's just a terminal, nothing more, nothing less.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(granite)
    - pkgconfig(vte-2.91)
    - vala
setup      : |
    %patch -p1 < $pkgfiles/0001-Remove-unnecessary-tests.patch
    %meson_configure -Dubuntu-bionic-patched-vte=false
build      : |
    %ninja_build
install    : |
    %ninja_install
