name       : pantheon-terminal
version    : 0.4.3
release    : 12
source     :
    - https://launchpad.net/pantheon-terminal/0.4.x/0.4.3/+download/pantheon-terminal-0.4.3.tar.xz : 2f302e4fc8b3d430403f9732c78b2837d9ba8e674aab365dd97aafa760f70858
license    : GPL-3.0
summary    : A super lightweight, beautiful, and simple terminal.
component  : desktop
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(granite)
    - pkgconfig(vte-2.91)
    - vala
description: |
    A super lightweight, beautiful, and simple terminal. It's designed to be setup with sane defaults and little to no configuration. It's just a terminal, nothing more, nothing less.
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
