name       : pantheon-terminal
version    : 0.4.0.4
release    : 11
source     :
    - https://launchpad.net/pantheon-terminal/0.4.x/0.4.0.4/+download/pantheon-terminal-0.4.0.4.tar.xz : 91909f24de3d6bd6d6bee3e89c18e900cbaf04d88f85c36dfe6baaa9c69129fb
license    : GPL-3.0
summary    : A super lightweight, beautiful, and simple terminal.
component  : desktop
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(granite)
    - pkgconfig(vte-2.91)
    - vala
description: |
    A super lightweight, beautiful, and simple terminal. It's designed to be setup with sane defaults and little to no configuration. It's just a terminal, nothing more, nothing less.
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
